<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>IISLogExplorer</AssemblyName>
    <RootNamespace>IISLogExplorer.App</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>v.1.$([System.DateTime]::Now.ToString('yyMMddHHmm'))</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IISLogExplorer.Core\IISLogExplorer.Core.csproj" />
    <ProjectReference Include="..\IISLogExplorer.Infrastructure\IISLogExplorer.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="security-rules.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="settings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
